## 端口号  上下文路径
server:
  port: 9999
  servlet:
    context-path: /shiro

## 数据源配置
spring:
  datasource:
    type: com.mchange.v2.c3p0.ComboPooledDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/shiro_test?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8
    username: root
    password: root
## mybatis 配置
mybatis:
  mapper-locations: classpath:/mappers/*.xml
  type-aliases-package: com.smy.vo;com.smy.mapper
  configuration:
    map-underscore-to-camel-case: true

## 设置 dao 日志打印级别
logging:
  level:
    com:
      smy:
          mapper: debug